server:
    port:  7415                                                             # 服务器端口
    token: XIv3ybWOTIR2Md3sKuMk6AgqjBUH48IRK2d9RMqHGeVymDwc9AWMFOWV7lXc3foJ # 令牌
db:
    max_open_conns: 10                                                      # 最大连接数
    max_idle_conns: 5                                                       # 最大空闲连接数
    reset: true                                                             # 是否重置数据库
image:
    key_length: 8                                                          #key长度
    max_size: 20                                                           # 图片最大大小(MB)
    path: ./localimage                                                     # 图片存储路径
    image_list_defalut_size: 10                                            # 图片列表默认大小
    compression_quality: 6                                                 # 图片压缩质量(1-6, 1最低质量, 质量越低速度越快)
    url: http://127.0.0.1:7415                                             # 返回图片的url前缀