server:
  port: 7415
  path: ./localimage
  host: http://127.0.0.1:7415
  image_list_defalut_size: 10
  token: XIv3ybWOTIR2Md3sKuMk6AgqjBUH48IRK2d9RMqHGeVymDwc9AWMFOWV7lXc3foJ
db:
  host: yuki-image-db
  port: 3306
  name: yuki_image_db
  user: yuki-image
  password: yuki-image
  max_open_conns: 10
  max_idle_conns: 5