server:
  port: 7415
  path: ./localimage
  host: http://127.0.0.1:7415
  token: XIv3ybWOTIR2Md3sKuMk6AgqjBUH48IRK2d9RMqHGeVymDwc9AWMFOWV7lXc3foJ
db:
  host: 8.134.48.192
  port: 3306
  name: yuki_image_db
  user: yuki_image
  password: yuki1234
  max_open_conns: 10
  max_idle_conns: 5