version: '3'
services:
    yuki-image:
        container_name: yuki-image
        image: crpi-jg7reu90mmam5qch.cn-guangzhou.personal.cr.aliyuncs.com/artdragon/yuki-image
        restart: no
        volumes:
            - ./config.yaml:/app/config.yaml
            - ./data/image:/app/localimage
            - ./data:/app/database
        ports:
            - 7415:7415
