version: '3'
services:
    yuki-image:
        container_name: yuki-image
        image: crpi-jg7reu90mmam5qch.cn-guangzhou.personal.cr.aliyuncs.com/artdragon/yuki-image
        restart: no
        volumes:
            - ./config.yaml:/app/config.yaml
            - ./data/image:/app/localimage
        ports:
            - 7415:7415
    mysql:
        image: mysql:8.0
        container_name: yuki-image-db
        restart: no
        hostname: yuki-image-db
        environment:
          - MYSQL_DATABASE=yuki_image_db
          - MYSQL_USER=yuki-image
          - MYSQL_PASSWORD=yuki-image
          - MYSQL_ROOT_PASSWORD=yuki-image
        volumes:
          - ./data/db:/var/lib/mysql
